
volumes:
  thriftbay-data: {}

services:
  fastapi:
    environment:
      CORS_HOST: ${CORS_HOST}
      SIGNING_KEY: ${SIGNING_KEY}
      DATABASE_URL: ${DATABASE_URL}
      STRIPE_PRIVATE_KEY: ${STRIPE_PRIVATE_KEY}
      PUBLIC_URL: ${PUBLIC_URL}
      WAIT_HOSTS: db:5432
      PORT: 8000


    build:
      context: api
      dockerfile: Dockerfile.dev

    ports:
      - 8000:8000


    volumes:
      - ./api:/app


  ghi:
    image: node:lts-bullseye
    command: /bin/bash run.sh
    working_dir: /app

    volumes:
      - ./ghi:/app


    ports:
      - "3000:3000"


    environment:
      HOST_OS: ${OS}
      NODE_ENV: development
      HOST: "0.0.0.0"
      PUBLIC_URL: ${PUBLIC_URL}
      REACT_APP_API_HOST: ${REACT_APP_API_HOST}


  db:
    image: postgres:14.5-bullseye
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_USER: admin
      POSTGRES_DB: thriftbay


    ports:
      - "15432:5432"
    volumes:
      - thriftbay-data:/var/lib/postgresql/data
